# Generated by Django 4.2.2 on 2023-06-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('created', models.DateField()),
                ('rate', models.CharField(choices=[('4', '4 Start'), ('5', '5 Start'), ('2', '2 Start'), ('1', '1 Start'), ('3', '3 Start')], max_length=20)),
                ('duration', models.CharField(max_length=10)),
                ('poster', models.ImageField(upload_to='')),
                ('director', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('series', 'series'), ('movie', 'movie')], max_length=50)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.genre')),
            ],
        ),
    ]
